version: '3.9'

services:
  service:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d vital_track" ]
      interval: 10s
      retries: 3
      timeout: 5s
      start_period: 5s
