name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.100'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run formatter tests
        run: |
          dotnet tool restore
          dotnet csharpier --check .